In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
%%time
df = pd.read_csv("C:/Users/Daniel/Desktop/proyecto/notebooks/todos_tweets.csv", sep = ";")

<string>:2: DtypeWarning: Columns (4,13) have mixed types.Specify dtype option on import or set low_memory=False.

Wall time: 2min 46s

In [5]:
df.head()

,date,time,username,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,retweet,video,reply_to,trend,month,day,hour,minute,second
0,2020-01-30,00:52:46,jandyta76,"Zeynep le dice a Faruk que no va a ir con él, ...",NaN,1,1,5.0,7.0,30.0,"zeymeh,i̇brahimçelikkol,demetözdemir,benimkaderim",0,0.0,NaN,Zeynep,01,30,00,52,46
1,2020-01-30,00:07:10,carlosozdemir,@Andrea45883391 Los 2 papá no quieren para nad...,NaN,1,1,0.0,0.0,0.0,benimkaderim,0,0.0,NaN,Zeynep,01,30,00,07,10
2,2020-01-29,23:59:28,demet_spain,"Mañana toca madrugar, así que os deseo que pas...",NaN,1,1,1.0,1.0,4.0,"demetozdemir,demetözdemir,doğduğunevkaderindir...",0,0.0,NaN,Zeynep,01,29,23,59,28
3,2020-01-29,23:36:12,rafirafi2412,@Andrea45883391 No hubo avance se quedo que a ...,NaN,1,1,1.0,3.0,3.0,NaN,0,0.0,NaN,Zeynep,01,29,23,36,12
4,2020-01-29,23:22:07,goalyolanda,Mejor la suegra de Zeynep k la madre Sakine #B...,NaN,1,1,1.0,3.0,2.0,benimkaderim,0,0.0,NaN,Zeynep,01,29,23,22,07

In [6]:
#df.isna().sum()/df.shape[0]*100

In [10]:
df_summary = pd.DataFrame(df_1.trend.value_counts()).reset_index()
df_summary.columns = ["trend", "total_count"]

In [11]:
df_summary["total_hashtags"] = [df_1[df_1.trend == trend].hashtags_count.sum() for trend in df_summary.trend]

df_summary["total_mentions"] = [df_1[df_1.trend == trend].mentions_count.sum() for trend in df_summary.trend]

df_summary["total_reply_to"] = [df_1[df_1.trend == trend].reply_count.sum() for trend in df_summary.trend]

df_summary["retweets_count"] = [df_1[df_1.trend == trend].retweets_count.sum() for trend in df_summary.trend]

df_summary["url_count"] = [df_1[df_1.trend == trend].urls.sum() for trend in df_summary.trend]

df_summary["photo_count"] = [df_1[df_1.trend == trend].photos.sum() for trend in df_summary.trend]

df_summary["likes_count"] = [df_1[df_1.trend == trend].likes_count.sum() for trend in df_summary.trend]

df_summary["interaction_count"] = [df_1[df_1.trend == trend].interaccion.sum() for trend in df_summary.trend]

In [12]:
tweet_count_labels = ["tweet_count_{}{}".format(i, i + 1) for i in range(24)]
time_intervals = ["0{}:00:00".format(i) if i < 10 else "{}:00:00".format(i) for i in range(24)] + ["23:59:59"]

for num, label in enumerate(tweet_count_labels):
    df_summary[label] = [df_1[(df_1.time.between(time_intervals[num], time_intervals[num + 1])) & (df_1.trend == trend)].shape[0] for trend in df_summary.trend]

In [13]:
tweet_vel_labels = ["tweet_vel_{}{}".format(i, i + 1) for i in range(24)]

velocidades = []
for i in range(df_summary.shape[0]):
    counts = [0] + list(df_summary.loc[i, tweet_count_labels])
    vel = [counts[i] - counts[i - 1] for i in range(1, len(counts))]
    velocidades.append(vel)
velocidades = np.array(velocidades)

In [14]:
df_summary = pd.concat([df_summary, pd.DataFrame(velocidades, columns = tweet_vel_labels)], axis = 1)

In [15]:
tweet_acl_labels = ["tweet_acl_{}{}".format(i, i + 1) for i in range(24)]

aceleraciones = []
for i in range(df_summary.shape[0]):
    counts = [0] + list(df_summary.loc[i, tweet_vel_labels])
    acl = [counts[i] - counts[i - 1] for i in range(1, len(counts))]
    aceleraciones.append(acl)
    
aceleraciones = np.array(aceleraciones)

In [16]:
df_summary = pd.concat([df_summary, pd.DataFrame(velocidades, columns = tweet_acl_labels)], axis = 1)

In [17]:
lifetime = []
for trend in df_summary.trend:
    start_end = list(df_1[df_1.trend == trend].sort_values("time").time.iloc[[0, -1]])
    start_end = int(start_end[1][0:2]) - int(start_end[0][0:2])
    lifetime.append(start_end)
    
df_summary["lifetime"] = lifetime

In [18]:
user_count_labels = ["user_count_{}{}".format(i, i + 1) for i in range(24)]

for num, label in enumerate(user_count_labels):
    df_summary[label] = [df_1[(df_1.time.between(time_intervals[num], time_intervals[num + 1])) & (df_1.trend == trend)].username.unique().shape[0] for trend in df_summary.trend]

In [19]:
df_summary

,trend,total_count,total_hashtags,total_mentions,total_reply,retweets_count,url_count,photo_count,likes_count,tweet_count_01,...,user_count_1415,user_count_1516,user_count_1617,user_count_1718,user_count_1819,user_count_1920,user_count_2021,user_count_2122,user_count_2223,user_count_2324
0,#OTDirecto24F,18056,20125,1280,613,66911.0,677,2033,418708.0,0,...,604,694,2169,887,466,459,493,476,471,386
1,González González,5991,2216,1727,8473,26694.0,1254,1192,69592.0,0,...,260,252,342,339,344,306,320,287,302,332
2,#ASUSWeekEnPcComponentes,2562,2609,193,3794,3400.0,12,78,1951.0,0,...,251,294,309,195,132,105,107,112,83,65
3,Falling,2076,185,68,176,5571.0,45,224,24340.0,0,...,0,0,698,352,203,124,95,70,64,47
4,#Coronavirius,1602,2872,299,198,13927.0,189,378,35086.0,0,...,41,113,100,66,94,109,239,314,186,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Calleri,1,0,0,0,0.0,0,0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
82,#AlavesAthleticEnGol,1,1,0,4,0.0,0,0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
83,Mollejo,1,0,0,0,0.0,0,1,0.0,1,...,0,0,0,0,0,0,0,0,0,0
84,Bergantiños,1,0,0,1,0.0,0,0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
85,#HoyTocaGala6,1,4,0,0,0.0,1,0,1.0,1,...,0,0,0,0,0,0,0,0,0,0