In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv("C:/Users/Daniel/Desktop/csv/dia 24/trends/dia_24_tendencias_variables.csv")
df.drop(df.columns[0], axis = 1, inplace = True)

In [17]:
for col in df.columns:
    print(col)

trend
total_count
total_hashtags
total_mentions
total_reply
retweets_count
url_count
photo_count
likes_count
tweet_count_01
tweet_count_12
tweet_count_23
tweet_count_34
tweet_count_45
tweet_count_56
tweet_count_67
tweet_count_78
tweet_count_89
tweet_count_910
tweet_count_1011
tweet_count_1112
tweet_count_1213
tweet_count_1314
tweet_count_1415
tweet_count_1516
tweet_count_1617
tweet_count_1718
tweet_count_1819
tweet_count_1920
tweet_count_2021
tweet_count_2122
tweet_count_2223
tweet_count_2324
tweet_vel_01
tweet_vel_12
tweet_vel_23
tweet_vel_34
tweet_vel_45
tweet_vel_56
tweet_vel_67
tweet_vel_78
tweet_vel_89
tweet_vel_910
tweet_vel_1011
tweet_vel_1112
tweet_vel_1213
tweet_vel_1314
tweet_vel_1415
tweet_vel_1516
tweet_vel_1617
tweet_vel_1718
tweet_vel_1819
tweet_vel_1920
tweet_vel_2021
tweet_vel_2122
tweet_vel_2223
tweet_vel_2324
tweet_acl_01
tweet_acl_12
tweet_acl_23
tweet_acl_34
tweet_acl_45
tweet_acl_56
tweet_acl_67
tweet_acl_78
tweet_acl_89
tweet_acl_910
tweet_acl_1011
tweet_acl_1112
tweet_acl_1213
tweet_acl_1314
tweet_acl_1415
tweet_acl_1516
tweet_acl_1617
tweet_acl_1718
tweet_acl_1819
tweet_acl_1920
tweet_acl_2021
tweet_acl_2122
tweet_acl_2223
tweet_acl_2324
lifetime
user_count_01
user_count_12
user_count_23
user_count_34
user_count_45
user_count_56
user_count_67
user_count_78
user_count_89
user_count_910
user_count_1011
user_count_1112
user_count_1213
user_count_1314
user_count_1415
user_count_1516
user_count_1617
user_count_1718
user_count_1819
user_count_1920
user_count_2021
user_count_2122
user_count_2223
user_count_2324

In [20]:
# Count
df.iloc[:, 9:33]

,tweet_count_01,tweet_count_12,tweet_count_23,tweet_count_34,tweet_count_45,tweet_count_56,tweet_count_67,tweet_count_78,tweet_count_89,tweet_count_910,...,tweet_count_1415,tweet_count_1516,tweet_count_1617,tweet_count_1718,tweet_count_1819,tweet_count_1920,tweet_count_2021,tweet_count_2122,tweet_count_2223,tweet_count_2324
0,1,3636,11628,7699,14871,6720,1769,133,47,56,...,343,349,276,253,262,207,191,160,159,184
1,1,1427,1279,1250,1222,1056,792,592,485,464,...,921,1118,1155,1210,1203,1185,1219,1182,1262,1363
2,0,650,253,156,42,41,31,122,245,503,...,1004,1140,4722,1538,744,664,777,985,911,613
3,2,5259,799,436,280,233,167,191,205,272,...,552,529,626,536,475,481,393,498,628,743
4,21,11741,752,217,63,79,72,125,152,147,...,97,100,57,32,26,24,36,32,16,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
205,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
206,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
# Velocidad
df.iloc[:, 33:57]

,tweet_vel_01,tweet_vel_12,tweet_vel_23,tweet_vel_34,tweet_vel_45,tweet_vel_56,tweet_vel_67,tweet_vel_78,tweet_vel_89,tweet_vel_910,...,tweet_vel_1415,tweet_vel_1516,tweet_vel_1617,tweet_vel_1718,tweet_vel_1819,tweet_vel_1920,tweet_vel_2021,tweet_vel_2122,tweet_vel_2223,tweet_vel_2324
0,1,3635,7992,-3929,7172,-8151,-4951,-1636,-86,9,...,81,6,-73,-23,9,-55,-16,-31,-1,25
1,1,1426,-148,-29,-28,-166,-264,-200,-107,-21,...,90,197,37,55,-7,-18,34,-37,80,101
2,0,650,-397,-97,-114,-1,-10,91,123,258,...,-193,136,3582,-3184,-794,-80,113,208,-74,-298
3,2,5257,-4460,-363,-156,-47,-66,24,14,67,...,46,-23,97,-90,-61,6,-88,105,130,115
4,21,11720,-10989,-535,-154,16,-7,53,27,-5,...,6,3,-43,-25,-6,-2,12,-4,-16,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,0,0,0,0,0,0,0,0,0,0,...,1,-1,0,1,-1,0,0,0,1,-1
205,0,0,0,0,0,0,0,1,-1,0,...,0,0,0,1,-1,0,0,0,0,0
206,0,0,0,1,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-1,0
207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,-1,0,0
208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# aceleracion
df.iloc[:, 57:81]

,tweet_acl_01,tweet_acl_12,tweet_acl_23,tweet_acl_34,tweet_acl_45,tweet_acl_56,tweet_acl_67,tweet_acl_78,tweet_acl_89,tweet_acl_910,...,tweet_acl_1415,tweet_acl_1516,tweet_acl_1617,tweet_acl_1718,tweet_acl_1819,tweet_acl_1920,tweet_acl_2021,tweet_acl_2122,tweet_acl_2223,tweet_acl_2324
0,1,3635,7992,-3929,7172,-8151,-4951,-1636,-86,9,...,81,6,-73,-23,9,-55,-16,-31,-1,25
1,1,1426,-148,-29,-28,-166,-264,-200,-107,-21,...,90,197,37,55,-7,-18,34,-37,80,101
2,0,650,-397,-97,-114,-1,-10,91,123,258,...,-193,136,3582,-3184,-794,-80,113,208,-74,-298
3,2,5257,-4460,-363,-156,-47,-66,24,14,67,...,46,-23,97,-90,-61,6,-88,105,130,115
4,21,11720,-10989,-535,-154,16,-7,53,27,-5,...,6,3,-43,-25,-6,-2,12,-4,-16,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,0,0,0,0,0,0,0,0,0,0,...,1,-1,0,1,-1,0,0,0,1,-1
205,0,0,0,0,0,0,0,1,-1,0,...,0,0,0,1,-1,0,0,0,0,0
206,0,0,0,1,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-1,0
207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,-1,0,0
208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0