In [1]:
import numpy as np
import pandas as pd

from scipy.ndimage.interpolation import shift

In [2]:
df_start_lifetime = pd.read_csv("C:/Users/Daniel/Desktop/csv/dia 24/trends/trends_24_start_lifetime.csv", sep = ";")

In [3]:
df_lifetime = pd.read_csv("C:/Users/Daniel/Desktop/csv/dia 24/trends/trends_24_lifetime.csv", sep = ";")

In [4]:
%%time
df = pd.read_csv("C:/Users/Daniel/Desktop/csv/dia 24/trends/tweets_24_tendencia_preprocesado.csv", sep = ";")

Wall time: 6.69 s

In [5]:
# Creo un nuevo df, df_summary donde se va a guardar los datos de los tweets

df_summary = pd.DataFrame(df.trend.unique())
df_summary.columns = ["trend"]

In [6]:
df_summary

                     trend
0    #SuperligaOrangeLoL12
1                #conquis6
2                 West Ham
3                fabianski
4                  Tavares
..                     ...
284                 Vitolo
285             #IFTasarte
286                Benzema
287               Garitano
288      Partido Feminista

[289 rows x 1 columns]

In [29]:
df_summary = pd.merge(left = df_summary, right = df_start_lifetime, on = "trend", how = "inner")

In [30]:
df_summary.start_lifetime = df_summary.start_lifetime.apply(lambda x : int(x[:2]))

In [31]:
df_summary = pd.merge(left = df_summary, right = df_lifetime, on = "trend", how = "inner")

# Variables de aggregacion

In [45]:
%%time

df_summary["total_tweet"]       = [df[(df.trend == t) & (df.hour.between(s, s + l))].tweet.shape[0] for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_hashtags"]    = [df[(df.trend == t) & (df.hour.between(s, s + l))].hashtags_count.sum() for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_mentions"]    = [df[(df.trend == t) & (df.hour.between(s, s + l))].mentions_count.sum() for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_reply_to"]    = [df[(df.trend == t) & (df.hour.between(s, s + l))].reply_to_count.sum() for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_url"]         = [df[(df.trend == t) & (df.hour.between(s, s + l))].urls.sum()           for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_photo"]       = [df[(df.trend == t) & (df.hour.between(s, s + l))].photos.sum()         for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_retweets"]    = [df[(df.trend == t) & (df.hour.between(s, s + l))].retweets_count.sum() for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_likes"]       = [df[(df.trend == t) & (df.hour.between(s, s + l))].likes_count.sum()    for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_replies"]     = [df[(df.trend == t) & (df.hour.between(s, s + l))].replies_count.sum()  for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

df_summary["total_interaction"] = [df[(df.trend == t) & (df.hour.between(s, s + l))].interaccion.sum()    for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

Wall time: 4min 50s

# Variables de tiempo

In [46]:
df[df.trend == df_summary.trend.unique()[5]]

,id,date,time,username,tweet,mentions,urls,photos,replies_count,retweets_count,...,trend,month,day,hour,minute,second,mentions_count,reply_to_count,hashtags_count,interaccion
3503,1232077732152070145,2020-02-24,23:59:56,rviozquez,firstdatesf menudo personaje tio guapa buena c...,NaN,0,1,0.0,1.0,...,#FirstDates24F,2,24,23,59,56,1,1,1,10.0
3504,1232077649503191040,2020-02-24,23:59:37,caotica95,ole coñoooooooooooooo firstdatesf,NaN,0,0,0.0,0.0,...,#FirstDates24F,2,24,23,59,37,1,1,1,1.0
3505,1232077211139805185,2020-02-24,23:57:52,caotica95,van camarote firstdatesf,NaN,0,1,0.0,0.0,...,#FirstDates24F,2,24,23,57,52,1,1,1,2.0
3506,1232077044751773697,2020-02-24,23:57:13,caotica95,raquel date cuenta vuelvas gilipollas firstdatesf,NaN,0,0,0.0,0.0,...,#FirstDates24F,2,24,23,57,13,1,1,1,6.0
3507,1232076593960452096,2020-02-24,23:55:25,caotica95,awwwwwwwwww cuquiiiisssssssss firstdatesf,NaN,0,0,0.0,0.0,...,#FirstDates24F,2,24,23,55,25,1,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4664,1232034700547502082,2020-02-24,21:08:57,_javitus_,siguiera toda gente dado like tendria seguidor...,NaN,0,1,1.0,1.0,...,#FirstDates24F,2,24,21,8,57,1,1,1,8.0
4665,1232033788928167946,2020-02-24,21:05:20,dentrodlatv,encontrar amor bordo barco color noche nuevo p...,NaN,1,0,0.0,0.0,...,#FirstDates24F,2,24,21,5,20,1,1,1,0.0
4666,1232033448212258816,2020-02-24,21:03:58,dentrodlatv,puertas firstdatesf abren cuatrotv esperamos,NaN,1,0,0.0,0.0,...,#FirstDates24F,2,24,21,3,58,1,1,1,0.0
4667,1232032876578975744,2020-02-24,21:01:42,morillo1david,buenas noches venga lio firstdatesf,NaN,0,0,2.0,0.0,...,#FirstDates24F,2,24,21,1,42,1,1,1,11.0
4668,1232032103149264901,2020-02-24,20:58:38,david_h_a_m,firstdatesf bueno veamos frikis hoy,NaN,0,1,1.0,0.0,...,#FirstDates24F,2,24,20,58,38,1,1,1,8.0

In [49]:
ddd = [df[(df.trend == t) & (df.hour.between(s, s + l))].shape[0] for t, s, l in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime)]

In [ ]:
lista = list()
for trend, start, life in zip(df_summary.trend, df_summary.start_lifetime, df_summary.lifetime):
    hours = [i if i in list(range(start, start + life)) else 0 for i in range(12)]
    lista.append(l)

In [51]:
start = 2
life = 4

In [52]:
hours = [i if i in list(range(start, start + life)) else 0 for i in range(12)]
hours

[0, 0, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0]

In [12]:
time_intervals = ["0{}:00:00".format(i) if i < 10 else "{}:00:00".format(i) for i in range(12)] + ["11:59:59"]

In [13]:
# Bucle que calcula el conteo de tweets para cada hora y para cada tendencia

tweet_count_labels = ["tweet_count_{}{}".format(i, i + 1) for i in range(12)]

for num, label in enumerate(tweet_count_labels):
    df_summary[label] = [df[(df.time.between(time_intervals[num], time_intervals[num + 1])) & (df.trend == trend)].shape[0] for trend in df_summary.trend]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-a816ce9832df>", line 6, in <module>
    df_summary[label] = [df[(df.time.between(time_intervals[num], time_intervals[num + 1])) & (df.trend == trend)].shape[0] for trend in df_summary.trend]
  File "<ipython-input-13-a816ce9832df>", line 6, in <listcomp>
    df_summary[label] = [df[(df.time.between(time_intervals[num], time_intervals[num + 1])) & (df.trend == trend)].shape[0] for trend in df_summary.trend]
  File "C:\Users\Daniel\anaconda3\lib\site-packages\pandas\core\series.py", line 4365, in between
    rmask = self <= right
  File "C:\Users\Daniel\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 64, in new_method
    return method(self, other)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\pandas\core\ops\__init__.py", line 526, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 247, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 58, in comp_method_OBJECT_ARRAY
    return result.reshape(x.shape)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
OSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '<ipython-input-13-a816ce9832df>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\Daniel\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\Daniel\anaconda3\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Users\Daniel\anaconda3\lib\inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Users\Daniel\anaconda3\lib\inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "C:\Users\Daniel\anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt

KeyboardInterrupt:

In [ ]:
# Bucle que calcula las velocidades restando la cantidad de tweets para cada hora y cada tendencias

tweet_vel_labels = ["tweet_vel_{}{}".format(i, i + 1) for i in range(12)]

velocidades = []
for i in range(df_summary.shape[0]):
    counts = [0] + list(df_summary.loc[i, tweet_count_labels])
    vel = [counts[i] - counts[i - 1] for i in range(1, len(counts))]
    velocidades.append(vel)
    
velocidades = np.array(velocidades)

df_summary = pd.concat([df_summary, pd.DataFrame(velocidades, columns = tweet_vel_labels)], axis = 1)

In [ ]:
# Bucle que calcula las aceleraciones restando las velocidades de cada hora y para cada tendencia 

tweet_acl_labels = ["tweet_acl_{}{}".format(i, i + 1) for i in range(12)]

aceleraciones = []
for i in range(df_summary.shape[0]):
    counts = [0] + list(df_summary.loc[i, tweet_vel_labels])
    acl = [counts[i] - counts[i - 1] for i in range(1, len(counts))]
    aceleraciones.append(acl)
    
aceleraciones = np.array(aceleraciones)

df_summary = pd.concat([df_summary, pd.DataFrame(aceleraciones, columns = tweet_acl_labels)], axis = 1)

In [ ]:
# Bucle que calcula la cantidad de usuarios unicos que han tweeteado por cada hora y cada tendencia

user_count_labels = ["user_count_{}{}".format(i, i + 1) for i in range(12)]

for num, label in enumerate(user_count_labels):
    df_summary[label] = [df[(df.time.between(time_intervals[num], time_intervals[num + 1])) & (df.trend == trend)].username.unique().shape[0] for trend in df_summary.trend]

In [ ]:
# Guarda el df_summary en un csv
#df_summary.to_csv("tweets_24_tendencia_variables.csv", sep = ";", index = False)